# Generated by Django 5.0.1 on 2024-01-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_products_alter_students_address_alter_students_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('speed', models.IntegerField(default=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
